### ISSUE TITLE
Naive Models

### ISSUE THREAD

**Issue by bturkoglu** [RaneemQaddoura/EvoCluster#3]
Thanks for vey nice job.
Can you add pure models to compare the performance of nature inspired algorithms like k means?

**Comment by RaneemQaddoura** [comment]
Thank you.
EvoCluster is limited to evolutionary computation algorithms.
The other algorithms you are referring to can be found at scikit learn. You can easily apply the datasets on scikit learn in a few lines of code to compare it with the ones at EvoCluster.
