### ISSUE TITLE
Problem in installing

### ISSUE THREAD

**Issue by bappa10085** [RaneemQaddoura/EvoCluster#4]
I was trying to install EvoCluster in Python 3.6 using command prompt in Windows 10. I am getting the following error
C:\Python36\Scripts>pip3 install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

The link https://www.continuum.io/downloads is not opening. Please help me how can I install EvoCluster for Anaconda?

**Comment by RaneemQaddoura** [comment]
Hi

You can watch the following tutorial to use the framework:
https://www.youtube.com/watch?v=TOIo9WMBWUc

You also can watch the following introductory video for EvoCluster
https://www.youtube.com/watch?v=3DYIdxILZaw

Good Luck

**Comment by RaneemQaddoura** [comment]
.
